# Generated by Django 3.1.7 on 2021-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrariumapp', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
