# Generated by Django 3.1.7 on 2021-04-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrariumapp', '0004_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
